
import { Question } from '@/types/quiz';

export const dockerQuestions: Question[] = [
  {
    question: "What is Docker and what problem does it solve?",
    options: [
      "A programming language for web development",
      "A containerization platform that packages applications with their dependencies",
      "A database management system",
      "A cloud storage service"
    ],
    correct: 1,
    explanation: "Docker is a containerization platform that allows you to package applications with all their dependencies into lightweight, portable containers."
  },
  {
    question: "What is the difference between a Docker image and a Docker container?",
    options: [
      "There is no difference, they are the same thing",
      "An image is a running instance, a container is a template",
      "An image is a template/blueprint, a container is a running instance",
      "Images are smaller than containers"
    ],
    correct: 2,
    explanation: "A Docker image is a read-only template used to create containers, while a container is a running instance of an image."
  },
  {
    question: "Which command is used to build a Docker image from a Dockerfile?",
    options: [
      "docker create",
      "docker build",
      "docker make",
      "docker compile"
    ],
    correct: 1,
    explanation: "The 'docker build' command is used to build a Docker image from a Dockerfile."
  },
  {
    question: "What is the purpose of the FROM instruction in a Dockerfile?",
    options: [
      "To copy files from host to container",
      "To specify the base image for the Docker image",
      "To set environment variables",
      "To expose ports"
    ],
    correct: 1,
    explanation: "The FROM instruction specifies the base image that the new image will be built upon."
  },
  {
    question: "How do you run a Docker container in detached mode?",
    options: [
      "docker run -d <image>",
      "docker run -detach <image>",
      "docker run --background <image>",
      "docker run -b <image>"
    ],
    correct: 0,
    explanation: "The -d flag runs a container in detached mode (in the background)."
  },
  {
    question: "What is Docker Compose used for?",
    options: [
      "To compress Docker images",
      "To define and run multi-container Docker applications",
      "To compose Dockerfiles automatically",
      "To merge multiple Docker images"
    ],
    correct: 1,
    explanation: "Docker Compose is a tool for defining and running multi-container Docker applications using a YAML file."
  },
  {
    question: "Which instruction in Dockerfile is used to copy files from host to container?",
    options: [
      "MOVE",
      "COPY",
      "TRANSFER",
      "ADD"
    ],
    correct: 1,
    explanation: "The COPY instruction copies files or directories from the host filesystem to the container filesystem."
  },
  {
    question: "What is the difference between COPY and ADD instructions in Dockerfile?",
    options: [
      "No difference, they are identical",
      "ADD can extract tar files and download URLs, COPY cannot",
      "COPY can extract tar files, ADD cannot",
      "ADD is deprecated, only COPY should be used"
    ],
    correct: 1,
    explanation: "ADD has additional features like extracting tar files and downloading from URLs, while COPY is more straightforward and preferred for simple file copying."
  },
  {
    question: "How do you expose a port in a Dockerfile?",
    options: [
      "PORT 8080",
      "EXPOSE 8080",
      "OPEN 8080",
      "LISTEN 8080"
    ],
    correct: 1,
    explanation: "The EXPOSE instruction informs Docker that the container listens on the specified network port at runtime."
  },
  {
    question: "What is a Docker volume used for?",
    options: [
      "To increase container performance",
      "To persist data and share data between containers",
      "To compress container size",
      "To speed up container startup"
    ],
    correct: 1,
    explanation: "Docker volumes are used to persist data generated by and used by Docker containers, and to share data between containers."
  },
  {
    question: "How do you list all running Docker containers?",
    options: [
      "docker list",
      "docker ps",
      "docker containers",
      "docker show"
    ],
    correct: 1,
    explanation: "The 'docker ps' command lists all currently running containers."
  },
  {
    question: "What is the purpose of .dockerignore file?",
    options: [
      "To ignore Docker commands",
      "To specify files and directories to exclude from the build context",
      "To ignore Docker containers",
      "To hide Docker images"
    ],
    correct: 1,
    explanation: "The .dockerignore file specifies files and directories that should be excluded from the build context sent to the Docker daemon."
  },
  {
    question: "How do you remove a Docker container?",
    options: [
      "docker delete <container_id>",
      "docker rm <container_id>",
      "docker remove <container_id>",
      "docker del <container_id>"
    ],
    correct: 1,
    explanation: "The 'docker rm' command removes one or more containers."
  },
  {
    question: "What is Docker Hub?",
    options: [
      "A Docker development environment",
      "A cloud-based registry service for Docker images",
      "A Docker monitoring tool",
      "A Docker orchestration platform"
    ],
    correct: 1,
    explanation: "Docker Hub is a cloud-based registry service that allows you to link to code repositories, build images, and test them."
  },
  {
    question: "How do you check the logs of a Docker container?",
    options: [
      "docker log <container_id>",
      "docker logs <container_id>",
      "docker show-logs <container_id>",
      "docker view <container_id>"
    ],
    correct: 1,
    explanation: "The 'docker logs' command fetches the logs of a container."
  },
  {
    question: "What is the purpose of WORKDIR instruction in Dockerfile?",
    options: [
      "To set the working directory for subsequent instructions",
      "To create a new directory",
      "To change file permissions",
      "To set environment variables"
    ],
    correct: 0,
    explanation: "WORKDIR sets the working directory for any RUN, CMD, ENTRYPOINT, COPY, and ADD instructions that follow it."
  },
  {
    question: "How do you tag a Docker image?",
    options: [
      "docker tag <image_id> <tag_name>",
      "docker name <image_id> <tag_name>",
      "docker label <image_id> <tag_name>",
      "docker rename <image_id> <tag_name>"
    ],
    correct: 0,
    explanation: "The 'docker tag' command creates a tag that refers to an existing image."
  },
  {
    question: "What is the difference between CMD and ENTRYPOINT in Dockerfile?",
    options: [
      "No difference, they are identical",
      "CMD is always executed, ENTRYPOINT can be overridden",
      "ENTRYPOINT is always executed, CMD can be overridden",
      "CMD is for Linux, ENTRYPOINT is for Windows"
    ],
    correct: 2,
    explanation: "ENTRYPOINT is always executed and cannot be overridden, while CMD provides default arguments that can be overridden."
  },
  {
    question: "How do you execute a command inside a running Docker container?",
    options: [
      "docker run <container_id> <command>",
      "docker exec <container_id> <command>",
      "docker execute <container_id> <command>",
      "docker cmd <container_id> <command>"
    ],
    correct: 1,
    explanation: "The 'docker exec' command runs a command in a running container."
  },
  {
    question: "What is Docker Swarm?",
    options: [
      "A Docker image compression tool",
      "A native clustering and orchestration solution for Docker",
      "A Docker security scanner",
      "A Docker image registry"
    ],
    correct: 1,
    explanation: "Docker Swarm is Docker's native clustering and orchestration solution for managing a cluster of Docker engines."
  }
];

// Add more questions to reach 100 total
const additionalDockerQuestions: Question[] = [
  {
    question: "What is multi-stage build in Docker?",
    options: [
      "Building multiple images at once",
      "A technique to reduce image size by using multiple FROM statements",
      "Building images in multiple environments",
      "A method to build images faster"
    ],
    correct: 1,
    explanation: "Multi-stage builds allow you to use multiple FROM statements in a Dockerfile to reduce the final image size."
  },
  {
    question: "How do you push a Docker image to Docker Hub?",
    options: [
      "docker push <image_name>",
      "docker upload <image_name>",
      "docker publish <image_name>",
      "docker deploy <image_name>"
    ],
    correct: 0,
    explanation: "The 'docker push' command uploads an image to a Docker registry like Docker Hub."
  },
  {
    question: "What is the purpose of the RUN instruction in Dockerfile?",
    options: [
      "To run the container",
      "To execute commands during image build",
      "To run commands when container starts",
      "To run background processes"
    ],
    correct: 1,
    explanation: "RUN executes commands during the image build process and creates a new layer."
  },
  {
    question: "How do you stop a running Docker container?",
    options: [
      "docker stop <container_id>",
      "docker kill <container_id>",
      "docker halt <container_id>",
      "docker pause <container_id>"
    ],
    correct: 0,
    explanation: "The 'docker stop' command stops a running container gracefully."
  },
  {
    question: "What is the default network driver in Docker?",
    options: [
      "host",
      "bridge",
      "overlay",
      "none"
    ],
    correct: 1,
    explanation: "Bridge is the default network driver in Docker, providing isolated networks for containers."
  }
];

export const allDockerQuestions = [...dockerQuestions, ...additionalDockerQuestions];
